### ISSUE TITLE
Event.Ack() does not return the error from event.susi.Ack

### ISSUE THREAD

**Issue by niondir** [webvariants/susigo#3]
The Ack method on the event is a useful helper but does not return the error.

Since I like to handle the error I would suggest to simply return it.

**Comment by trusch** [comment]
Sounds reasonable. The event interface needs a refactoring, this will not be the only issue like that I think.

Feel free to start a PR, otherwise I will have a look at it next week.

**Comment by trusch** [comment]
For now you can use the old API with susi.Ack(event)

**Comment by trusch** [comment]
This is fixed by the [latest commit](https://github.com/webvariants/susigo/commit/5cd74a28fbd5a2a2fec00ce0abda2e9e408d8f91)
